services:

  # ======== PostgreSQL
  db:
    image: postgres:16
    container_name: admindashboard-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - admindashboard-network



  # ======== API
  api:
    container_name: admindashboard-api
    build:
      context: .
      dockerfile: AdminDashboard.Api/Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Default: Host=${POSTGRES_HOST};Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__AccessTokenMinutes: ${JWT_ACCESS_TOKEN_MINUTES}
      Jwt__RefreshTokenDays: ${JWT_REFRESH_TOKEN_DAYS}
    ports:
      - "5000:8080"
    networks:
      - admindashboard-network



# ======== Volumes
volumes:
  postgres_data:



# ======== Network
networks:
  admindashboard-network:
    driver: bridge